stackprj/stackbase/urls.py
from django.urls import path
from . import views

app_name = 'stackbase'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('questions/',views.QuestionListView.as_view(),name="question_list"),
    path('questions/new',views.QuestionCreateView.as_view(),name="question_create"),
    path('questions/<int:pk>',views.QuestionDetailView.as_view(),name="question_detail"),
    path('questions/<int:pk>/update/',views.QuestionUpdateView.as_view(),name="question_update"),
    path('questions/<int:pk>/delete', views.QuestionDeleteView.as_view(), name="question_delete"),
    path('questions/<int:pk>/comment/',views.AddCommentView.as_view(),name="question_comment"),

]

stackprj/stackprj/urls.py
from django.contrib import admin
from django.urls import path, include
from stackusers import views as user_views
from stackbase import views as base_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackbase.urls')),
    path('register',user_views.registerPage,name="register"),
    #path('login',auth_views.LoginView.as_view(template_name="stackusers/login.html"),name="login"),
    path('login',user_views.loginPage,name="login"),
    path('logout',auth_views.LogoutView.as_view(template_name="stackusers/logout.html"),name="logout"),
    path('profile',user_views.profilePage,name="profile"),
    path('profile/update',user_views.profileUpdatePage,name="profile_update"),
    path('questions',base_views.QuestionListView.as_view(template_name="stackbase/question_list.html")),
    path('questions/<int:pk>',base_views.QuestionDetailView.as_view(template_name="stackbase/question_detail.html")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stackprj/stackbase/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User

class Question(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    title = models.CharField(max_length = 1000)
    content = models.TextField(null=True,blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self,):
        return f'{self.user.username} - Question'
    
    def get_absolute_url (self):
        return reverse('stackbase:question_detail', kwargs={'pk':self.pk})

class Comment(models.Model):
    question = models.ForeignKey(Question, related_name="comment", on_delete=models.CASCADE)
    name = models.CharField(max_length = 1000)
    content = models.TextField(null=True, blank=True)
    date_created = models.DateTimeField(default=timezone.now)

    def __str__(self):
        return '%s - %s' % (self.question.title, self.question.user)

    def get_absolute_url(self):
        return reverse('stackbase:question-detail', kwargs={'pk':self.pk})

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

stackprj/stackbase/forms.py
from .models import Comment
from django import forms

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ['name', 'content']

        widgets = {
            'name': forms.TextInput(attrs={'class': 'form-control'}),
            'content': forms.Textarea(attrs={'class': 'form-control'}),
        }

stackprj/stackbase/views.py
from django.shortcuts import render
from django.views.generic import ListView,DetailView,CreateView,UpdateView,DeleteView
from django.contrib.auth.mixins import LoginRequiredMixin,UserPassesTestMixin
from .models import Question, Comment
from .forms import CommentForm
from django.urls import reverse, reverse_lazy

def home(request):
    return render(request, 'home.html')

def about(request):
    return render(request, 'base.html')

class QuestionListView(ListView):
    model = Question
    context_object_name = 'question'
    ordering = ['-date_created']

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        search_input = self.request.GET.get('search-area') or ""
        if search_input:
            context['question'] = context['question'].filter(title__icontains = search_input)
            context['search_input'] = search_input
        return context

class QuestionDetailView(DetailView):
    model = Question
    context_object_name = 'question'

class QuestionCreateView(CreateView):
    model = Question
    fields =['title','content']
    context_object_name = 'question'
    def form_valid(self,form):
        form.instance.user=self.request.user
        return super().form_valid(form)
    
class QuestionUpdateView(UpdateView):
    model = Question
    fields =['title','content']
    context_object_name = 'question'
    def form_valid(self, form):
         form.instance.user = self.request.user
         return super().form_valid(form)
    def test_func(self):
         questions = self.get_object()
         if self.request.user == questions.user:
            return True
         return False
class QuestionDeleteView(UserPassesTestMixin,DeleteView):
    model = Question
    context_object_name = 'question'
    success_url="/"
    template_name = 'stackbase/question_confirm_delete.html'

    def test_func(self):
        questions= self.get_object()
        if self.request.user == questions.user:
            return True
        return False
class CommentDeatilView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'stackbase/question_detail.html'

    def form_valid(self,meta):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)

    success_url = reverse_lazy('stackbase:question_detail')

class AddCommentView(CreateView):
    model = Comment
    form_class = CommentForm
    template_name = 'stackbase/question_answer.html'

    def form_valid(self,form):
        form.instance.question_id = self.kwargs['pk']
        return super().form_valid(form)
    success_url = reverse_lazy('stackbase:question_list')

stackprj/stackbase/templates/stackbase/question_answer.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}

{% block content %}
    <!DOCTYPE html>
    <html lang="en">
    <head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
        <script src="https://unpkg.com/feather-icons"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">

        <style>

          body {
            background-color: #8fd6f9;
        }

        h6 {
            font-size: 15px;
            font-family: 'Poppins', sans-serif;

        }

         .btn-post {
            background-color: #fba34a;
            font-size: 13px;
            border: none;
            color: black;
            font-family: 'Poppins', sans-serif;
            margin: 14px 80px;
        }
        .btn-post:hover {
        background-color: #d67200;
        }

        .centered-container {
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
            width: 50%;
            padding: 20px;
            margin: auto;
            background-color: #fff;

            border-radius: 20px;
            -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
            box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
            border: none;
            margin-bottom: 30px;
            line-height: 25px;

        }


        </style>
    </head>
    <body>
    <div style="margin-top:150px;"> </div>

<div class="centered-container">
    <form action="" method="POST">
        <h6> {% csrf_token %} </h6>
        <h6> {{form|crispy}} </h6>
        <h6> {{ form.media }} </h6>
        <button class="btn btn-post" id="logout-btn" type="submit">Post Answer</button>
        <a style="text-decoration: none;margin-top:20px;" href="{% url 'stackbase:question_list' %}">Cancel</a>
    </form>
</div>

    <div style="margin-bottom:250px;"> </div>
    </body>
    </html>
{% endblock content %}

stackprj/stackbase/templates/stackbase/question_confirm_delete.html
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<html>

<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <script src="https://unpkg.com/feather-icons"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">

        <style>

        body {
            background-color: #f9c78f;
        }

        h6 {
            font-size: 15px;
            font-family: 'Poppins', sans-serif;

        }


  .btn {
    text-align: center;
    border-radius: 3px;
    transition: all 0.5s;
    padding: 1.3rem 2.5rem;
  }

        .btn-post {
            background-color: #fba34a;
            font-size: 15px;
            border: none;
            color: black;
            font-family: 'Poppins', sans-serif;
            margin: 14px 80px;
        }
        .btn-post:hover {
        background-color: #d67200;
        }

        .centered-container {
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
            width: 50%;
            padding: 20px;
            margin: auto;
            background-color: #fff;

            border-radius: 20px;
            -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
            box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
            border: none;
            margin-bottom: 30px;
            line-height: 25px;

        }

        .info-container{
            float:left;
        }

        </style>
    </head>

<body>

<div style="margin-top:150px;"> </div>

<div class="centered-container">
    <form action="" method="POST">
            {% csrf_token %}
            <div class="info-container">
                <h6 id="fh3">Are you sure you want to delete this question?
                    <h6>{{ question.title }} </h6>

                <div class="container">
                    <button class="btn btn-post" type="submit" >Delete</button>
                    <button class="btn btn-post" type="submit" ><a href="{% url 'stackbase:question_detail' question.id %}">Cancel</a></button>
                </div>
            </div>
        </form>
    </div>


<div style="margin-bottom:150px;"> </div>
</body>

</html>
{% endblock %}

stackprj/stackbase/templates/stackbase/question_detail.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        /* .list-question{
            height: 400px;
            background-color: rgb(255, 219, 173);
        } */
        #fh3{
            text-align: center;
            font-size: 30px;
            padding-top: 20px;
            text-align: left;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 17px;
                text-align: left;
            }
        }
        #fh6{
            text-align: left;
            font-size: 15px;
            /* padding-top: 20px; */
            padding-bottom: 20px;
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: left;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }

         .btn-outline{
       padding: 10px 20px;
         outline: none;
        background-color: transparent;
        cursor: pointer;
        }
        .btn-outline:hover {
            color: #fff;
        }

        .blue {
         border: 2px solid #2592d4;
        color: #2592d4;
        }
        .blue:hover {
            border: 2px solid #2592d4;
            background-color: #2592d4;
        }

        .green {
         border: 2px solid #27a718;
        color: #27a718;
        }
        .green:hover {
            border: 2px solid #27a718;
            background-color: #27a718;
        }
         .red {
         border: 2px solid #d52f2f;
        color: #d52f2f;
        }
        .red:hover {
            border: 2px solid #d52f2f;
            background-color: #d52f2f;
        }
         .gray {
         border: 2px solid #7a7a7a;
        color: #7a7a7a;
        }
        .gray:hover {
            border: 2px solid #7a7a7a;
            background-color: #7a7a7a;
        }

    </style>
</head>
<body>
    <div class="container">
        <div id="sub-nav">
        </div>
        <div class="list-question">
            <div class="questions">
                <div class="container" style="background-color: rgba(255, 235, 209, 0.808); padding: 5px; box-shadow: rgba(0, 0, 0, 0.15) 0px 5px 5px 0px; border-radius: 20px;" >
                    <h3 id="fh3">{{question.title}}</h3>
                    <hr>
                    <h6 id="fh6" style="margin-top:20px">{{ question.content|safe }}</h6>
                    <hr>
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155); text-align: right;">Asked By: <a href="{% url 'profile' %}">{{ object.user|title }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{ object.date_created|date:"j F, Y" }}</h6>
                    <br>

                    <h2>Answers...</h2> <br><br><br>

                    {% if not question.comment.all %}
                        <h3>No Answers yet... <a href="">Answer Question</a> </h3>
                    {% else %}
                        {% for comment in question.comment.all %}
                            <h3 style="font-weight: normal; font-size: 15px;">{{comment.content|safe}}</h3>
                            <h3 style="font-size: 12px;">Answered by: <i><a href="">{{comment.name}}</a> - On: {{comment.date_created|date:"j F, Y"}}</i></h3>
                            <hr>
                        {% endfor %}
                    {% endif %}

                    <div style="margin-top:30px;margin-bottom:20px">
                    <a class="btn btn-outline blue" id="fa" href="{% url 'stackbase:question_comment' question.id %}" style="text-decoration: none;">Answer Question</a>
                    <a class="btn btn-outline green" style="text-decoration: none;margin-left:850px"  href="{% url 'stackbase:question_update' question.id %}"> &#x270E;</a>
                    <a class="btn btn-outline red" style="text-decoration: none;"  href="{% url 'stackbase:question_delete' question.id %}">&#x2716;</a>
                    <a class="btn btn-outline gray" style="text-decoration: none;"  href="{% url 'stackbase:question_list' %}">&#x21a9;</a>
                    </div>
                </div>

                </div>
            </div>
        </div>
    </div>

<div style="margin-bottom:250px;"> </div>
</body>
</html>
{% endblock content %}

stackprj/stackbase/templates/stackbase/question_form.html
{% extends 'base.html' %}
{% load static %}
{% load crispy_forms_tags %}
{% block content %}
<html>

<head>
        <meta charset="UTF-8">
        <meta http-equiv="X-UA-Compatible" content="IE=edge">
        <meta name="viewport" content="width=device-width, initial-scale=1.0">
        <title></title>
        <script src="https://unpkg.com/feather-icons"></script>
        <link href="https://fonts.googleapis.com/css2?family=Poppins:wght@200&display=swap" rel="stylesheet">

        <style>

        body {
            background-color: #8fd6f9;
        }

        h6 {
            font-size: 15px;
            font-family: 'Poppins', sans-serif;

        }

        .btn-post {
            background-color: #fba34a;
            font-size: 13px;
            border: none;
            color: black;
            font-family: 'Poppins', sans-serif;
            margin: 14px 80px;
        }
        .btn-post:hover {
        background-color: #d67200;
        }

        .centered-container {
            display: flex;
            justify-content: center;
            align-items: center;
            overflow: hidden;
            width: 50%;
            padding: 20px;
            margin: auto;
            background-color: #fff;

            border-radius: 20px;
            -webkit-box-shadow: 0 1px 20px 0 rgba(69, 90, 100, 0.08);
            box-shadow: 0 1px 20px 0 rgba(53, 53, 53, 0.452);
            border: none;
            margin-bottom: 30px;
            line-height: 25px;

        }

        </style>
    </head>

<body>
    <div style="margin-top:150px;"> </div>

    <div class="centered-container">

        <div>
        <form action="" method="POST" >

            <h6> {% csrf_token %} </h6>
            <h6> {{ form|crispy }} </h6>

            <h6> <a href="{% url 'stackbase:question_list' %}" style="margin-top: 30px;">Cancel</a> </h6>
            <div><button class="btn btn-post" style="margin-top:30px" type="submit">Post Question</button></div>
        </form>
        </div>



    </div>

    <div style="margin-bottom:250px;"> </div>
</body>

</html>
{% endblock %}

stackprj/stackbase/templates/stackbase/question_list.html
{% extends 'base.html' %}
{% block content %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Document</title>
    <link href="https://fonts.googleapis.com/css2?family=Poppins:ital,wght@0,100;0,200;0,300;0,400;0,500;0,600;1,100;1,200;1,300;1,400;1,500&display=swap" rel="stylesheet">
    <!-- <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-F3w7mX95PdgyTmZZMECAngseQB83DfGTowi0iMjiWaeVhAn4FJkqJByhZMI3AhiU" crossorigin="anonymous"> -->
    <style>
        body{
            margin-top: 100px;
            font-family: 'Poppins', sans-serif;
        }
        #fh1{
            margin-top: 20px;
        }
        #sub-nav{
            display: flex;
            justify-content: space-around;
        }
        #logout-btn{
            background-color: rgb(50, 122, 255);
        }
        #fh3{
            text-align: left;
            font-size: 19px;
            padding-top: 15px;
        }
        @media screen and (max-width: 600px) {
            #fh3{
                font-size: 15px;
                text-align: left;
            }
        }
        #fh6{
            text-align: right;
            font-size: 15px;
            /* padding-bottom: 20px; */
            font-weight: normal;
        }
        @media screen and (max-width: 600px) {
            #fh6{
                font-size: 15px;
                text-align: right;
                font-weight: normal;
            }
        }
        #fh5{
            display: flex;
            justify-content: space-around;
            text-align: left;
            font-size: 13px;
            padding-top: 3px;
            width: 90px;
            color: rgb(223, 223, 223);
            height: 20px;
            font-weight: normal;
            background-color: rgb(158, 158, 158);
            border-radius: 20px;
            /* padding-top: 20px; */
            /* background-color: blue; */
        }
        @media screen and (max-width: 600px) {
            #fh5{
                font-size: 10px;
            }
        }
        a{
            color: rgb(0, 132, 255);
        }
        a:hover{
            text-decoration: none;
            color: darkblue;
            
        }
        h5{
            color: rgb(133, 133, 133);
        }
        .btn-ask {
            background-color: #74cfee;
            font-size: 13px;
            border: none;
            color: black;
            font-family: 'Poppins', sans-serif;
            margin: 4px 40px;
        }

        .btn-ask:hover {
        background-color: #559abe;
        }

    </style>
</head>
<body>
    <div class="container" >
        <div id="sub-nav">
            <h1 id="fh1">Top Questions</h1>
            {% if user.is_authenticated %}
            <button class="btn btn-ask"><a id="fa" href="{% url 'stackbase:question_create' %}" style="color: white; text-decoration: none;">Ask Question</a></button>
            {% else %}
            <button class="btn btn-ask"><a id="fa" href="{% url 'login' %}" style="color: white; text-decoration: none;">Ask Question</a></button>
            {% endif %}
        </div>
        <div class="list-question" style="margin-top:30px; margin-bottom:30px; padding:10px;">
            <div class="questions" >
                {% for question in question %}
                <div class="container" style="background: linear-gradient(to right, rgb(255, 226, 182), rgba(255, 166, 0, 0.027)); padding: 5px; box-shadow: rgba(0, 0, 0, 0.383) 0px 5px 5px 0px; border-radius: 15px;" >
                    <div id="title-sec" style="display: flex; align-items: center;">
                        <!-- <a href="{% url 'profile' %}"><img src="{{ request.user.profile.image.url }}" style="width: 50px;"></a></img> -->
                        <h3 id="fh3"><a href="{% url 'stackbase:question_detail' question.id%}">{{ question.title }}</a></h3>
                    </div>
                    <hr>
                    {% if question.content|wordcount <= 10 %}
                    <h6 id="fh6" style="text-align: left;">{{ question.content}}</h6>
                    {% else %}
                    <h6 id="fh6" style="text-align: left;">{{ question.content|truncatewords:10}} <a href="{% url 'stackbase:question_detail' question.id%}">Read More</a></h6>
                    {% endif %}
                    <h6 id="fh6" style="font-size: 10px; font-style: italic; color: rgb(155, 155, 155);">Asked By: <a href="{% url 'profile' %}">{{ question.user }}</a>&nbsp;&nbsp;&nbsp; |&nbsp;&nbsp;&nbsp; On: {{question.date_created|date:"j F, Y"}}</h6>
                    <h5 style="text-align: right; font-size: 12px; font-style: italic;">Tags</h5>
                </div> <br>
                {% endfor %}
            </div>
        </div>   
    </div>
</body>
</html>
{% endblock content %}