stackprj/stackbase/urls.py
from django.urls import path
from . import views

app_name = 'stackbase'

urlpatterns = [
    path('', views.home, name="home"),
    path('about/', views.about, name="about"),
    path('questions/',views.QuestionListView.as_view(),name="question_list"),
    path('questions/new',views.QuestionCreateView.as_view(),name="question_create"),
    path('questions/<int:pk>',views.QuestionDetailView.as_view(),name="question_detail"),
    path('questions/<int:pk>/update/',views.QuestionUpdateView.as_view(),name="question_update"),
    path('questions/<int:pk>/delete', views.QuestionDeleteView.as_view(), name="question_delete"),
    path('questions/<int:pk>/comment/',views.AddCommentView.as_view(),name="question_comment"),

]

stackprj/stackprj/urls.py
from django.contrib import admin
from django.urls import path, include
from stackusers import views as user_views
from stackbase import views as base_views
from django.contrib.auth import views as auth_views
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('stackbase.urls')),
    path('register',user_views.registerPage,name="register"),
    #path('login',auth_views.LoginView.as_view(template_name="stackusers/login.html"),name="login"),
    path('login',user_views.loginPage,name="login"),
    path('logout',auth_views.LogoutView.as_view(template_name="stackusers/logout.html"),name="logout"),
    path('profile',user_views.profilePage,name="profile"),
    path('profile/update',user_views.profileUpdatePage,name="profile_update"),
    path('questions',base_views.QuestionListView.as_view(template_name="stackbase/question_list.html")),
    path('questions/<int:pk>',base_views.QuestionDetailView.as_view(template_name="stackbase/question_detail.html")),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stackprj/templates/base.html
{% load static %}
<html lang="en">
<head>

    <meta charset="UTF-8">
    <meta name="viewport"
          content="width=device-width, user-scalable=no, initial-scale=1.0, maximum-scale=1.0, minimum-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title> FMIOverflow </title>
    <link rel="shortcut icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/favicon.ico?v=ec617d715196">
    <link rel="apple-touch-icon" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">
    <link rel="image_src" href="https://cdn.sstatic.net/Sites/stackoverflow/Img/apple-touch-icon.png?v=c78bd457575a">
    <link rel="stylesheet" href="{% static 'main.css' %}">

</head>

<body>
<header>

<div class="nav-container">
    <nav>
        <div class="nav-brand">
            <div class="hamburger-menu-container">
                <div class="hamburger-menu">
                    <div class="line"></div>
                    <div class="line"></div>
                    <div class="line"></div>
                </div>
                <div class="nav-dropdown-menu">

                    <ul class="nav-ul">
                        <li class="nav-item"><a href="#" class="current-link">Home</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Tags</a></li>
                        <li class="nav-item"><a href="#" class="nav-link">Users</a></li>
                    </ul>
                </div>
            </div>

            <a href="{% url 'stackbase:home' %}" style="text-decoration: none; color: black;">
                <div class="nav-icon-text">FMI <span class="nav-bold-text">Overflow</span> </div> </a>


        </div>

        <div class="nav-search" style="margin-left:100px; margin-right:100px">
            <div class="search-container">
                <i class="fas fa-search"></i>
                <form action="" method="GET">
                    <input type="text" id="" name="search-area" placeholder="Search...">
                    <button type="submit" style="margin-left: 340px; border-radius: 25px; border: none; padding: 8px;">Search</button>
                </form>
            </div>

            <div class="search-hints">
                <div class="search-arrow-up"></div>
                <div class="search-hint-body">
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>[tag] </span> search within a tag</div>
                        <div class="hint-text"><span>user:1234 </span>  search by author</div>
                        <div class="hint-text"><span>"words here"</span> exact phrase </div>
                    </div>
                    <div class="hints-grid-column">
                        <div class="hint-text"><span>answers:0</span> unanswered questions</div>
                        <div class="hint-text"><span> score:3  </span> posts with a 3+ score</div>
                    </div>
                </div>
                <div class="search-hint-footer">
                    <a href="#" class="btn">Ask a question</a>
                    <a href="#" class="search-help">Search help</a>
                </div>
            </div>

        </div>
        <div class="nav-right-buttons">
            <div class="search-btn">
                <i class="fas fa-search"></i>
            </div>
                {% if user.is_authenticated %}
                    <a href="{% url 'profile' %}" class="btn btn-login">Profile</a>
                    <a href="{% url 'logout' %}" class="btn btn-register">Logout</a>
                {% else %}
                    <a href="{% url 'login' %}" class="btn btn-login">Log in</a>
                    <a href="{% url 'register' %}" class="btn btn-register">Sign up</a>
                {% endif %}
        </div>
    </nav>
</div>
<!-- <h1 style="font-size: 20px;">hello</h1> -->
    <div style="margin-top: 10px;">
        {% if messages %}
        {% for message in messages %}
      <div class="alert alert-{{ message.tags }}" role="alert">
        <h4 style="text-align: center;">{{ message }}</h4>
      </div>
      {% endfor %}
    {% endif %}
    </div>


</header>

{% block content %}

{% endblock content %}

<footer class="footer">
    <img src="https://cdn.sstatic.net/Img/home/robot.svg?v=dfa16a330cbd" alt="" class="footer-robot-img">
<div class="container">
    <div class="footer-content">
        <div class="footer-icon">
            <i class="fab fa-stack-overflow"></i>
        </div>
        <div class="footer-nav">
            <div class="footer-nav-col">
                <div class="footer-links-title"><a href="#">FMIOverflow</a></div>
                <ul class="footer-links">
                    <li class="footer-link-item"><a href="#" class="footer-link">Questions</a></li>
                    <li class="footer-link-item"><a href="#" class="footer-link">Help</a></li>
                </ul>
            </div>
            <div class="footer-nav-col">
                <div class="footer-links-title"><a href="#">Others</a></div>
                <ul class="footer-links">
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Exemple1</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </li>
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Exemple2</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div></li>
                    <li class="footer-link-item">
                        <a href="#" class="footer-link">Exemple3</a>
                        <div class="footer-arrow-icon">
                            <i class="fas fa-chevron-right"></i>
                        </div>
                    </li>

                </ul>
            </div>
        </div>
        <div class="footer-another-links">
            <div class="social-media">
                <ul>
                    <li>
                        <a href="#">Blog</a>
                    </li>
                    <li>
                        <a href="#">Facebook</a>
                    </li>
                    <li>
                        <a href="#">Twitter</a>
                    </li>
                    <li>
                        <a href="#">LinkedIn</a>
                    </li>
                    <li>
                        <a href="#">Instagram</a>
                    </li>
                </ul>
            </div>
            <div class="copyright">
                <p>site design / logo © 2020 Stack Exchange Inc; user contributions licensed under <a href="https://stackoverflow.com/help/licensing">cc by-sa</a>. rev 2020.10.2.37725</p>
            </div>
        </div>
    </div>

</div>
</footer>

<!-- <script src="assets/js/main.js"></script> -->
<script src="{% static 'main.js' %}"></script>
<script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js" integrity="sha384-W8fXfP3gkOKtndU4JGtKDvXbO53Wy8SZCQHczT5FMiiqmQfUpWbYdTil/SxwZgAN" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.1.1/dist/js/bootstrap.min.js" integrity="sha384-skAcpIdS7UcVUC05LJ9Dxay8AXcDYfBJqt1CJ85S/CFujBsIzCIv+l9liuYLaMQ/" crossorigin="anonymous"></script>
</body>
</html>

stackprj/templates/home.html
{% extends 'base.html' %}
{% block content %}
<section class="hero">
    <div class="hero-content">
        <h1 class="hero-title">FMIOverflow</h1>
        <p class="hero-paragraph">
            A product that empowers developers and connect them to solutions that enable productivity, growth, and discovery.
        </p>
        <div class="hero-options">
            <a href="{% url 'stackbase:question_list' %}" class="btn btn-developers" style="margin-left: 5px;">Latest Questions</a>

        </div>
    </div>
</section>

<section class="for-developers">
   <div class="container">
       <div class="section-head">
           <h2 class="section-title">For developers, by developers
           </h2>
           <div class="section-line"></div>
           <p class="section-description"> FMIOverflow is an open community for anyone that codes. We help you get answers to your toughest coding questions and share knowledge with your collegues and coworkers in private.
           </p>
   </div>
</section>

<section class="questions">
    <div class="container">
       <div class="questions-content">
           <div class="questions-header">
               <h3 class="question-title">Questions are everywhere, answers are on FMIOverflow</h3>
           </div>
           <div class="questions-body">
               <div class="questions-body-items">
                   <div class="questions-body-item" data-id="0">
                       <img src="https://cdn.sstatic.net/Img/home/ask-a-question.svg?v=f4f2050b0297" alt="" class="question-item-icon">
                       <div class="question-item-text">Ask a question</div>
                       <div class="question-arrow-right"></div>
                   </div>
                   <div class="questions-body-item"  data-id="1">
                       <img src="https://cdn.sstatic.net/Img/home/votes.svg?v=748a8f48a8e2" alt="" class="question-item-icon">
                       <div class="question-item-text">Vote on everything</div>
                       <div class="question-arrow-right"></div>
                   </div >
                   <div class="questions-body-item"  data-id="2">
                       <img src="https://cdn.sstatic.net/Img/home/answer.svg?v=4cd8048a676c" alt="" class="question-item-icon">
                       <div class="question-item-text">Answer questions</div>
                       <div class="question-arrow-right"></div>
                   </div>
               </div>
               <div class="questions-body-item-content">
                   <img src="https://cdn.sstatic.net/Img/home/illo-feats-vote.svg?v=9d2eb0efdc17" alt="" class="question-item-content-img">
                   <h4 class="question-item-content-text">
                       Accept the answer which solved your problem to let others benefit from the valuable information.
                   </h4>
                   <a href="#" class="btn btn-orange question-item-content-btn">Create an account</a>
               </div>
               <div class="questions-body-items">
                   <div class="questions-body-item"  data-id="3">
                       <img src="https://cdn.sstatic.net/Img/home/tags.svg?v=913379eb09eb" alt="" class="question-item-icon">
                       <div class="question-item-text">Tag your question</div>
                       <div class="question-arrow-left"></div>
                   </div>
                   <div class="questions-body-item"  data-id="4">
                       <img src="https://cdn.sstatic.net/Img/home/accept.svg?v=27d5be078970" alt="" class="question-item-icon">
                       <div class="question-item-text">Accept a answer</div>
                       <div class="question-arrow-left"></div>
                   </div>
                   <div class="questions-body-item"  data-id="5">
                       <img src="https://cdn.sstatic.net/Img/home/get-recognized.svg?v=3b339d9aa10c" alt="" class="question-item-icon">
                       <div class="question-item-text">Get recognized</div>
                       <div class="question-arrow-left"></div>
                   </div>
               </div>
           </div>
       </div>
    </div>
</section>

{% endblock content %}

stackprj/templates/navbar.html
+
{% block content %}
<a href="/about">
    <h1> testing </h1>
</a>
<a href="">
    <h1> tested </h1>
</a>
{% endblock %}